/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

/**
 *
 * @author Administrator
 */
public class Datos_Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Datos_Clientes
     */
    public Datos_Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        txt_dia = new javax.swing.JComboBox<>();
        txt_mes = new javax.swing.JComboBox<>();
        txt_año = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(809, 470));
        setMinimumSize(new java.awt.Dimension(809, 470));

        jPanel1.setMaximumSize(new java.awt.Dimension(809, 470));
        jPanel1.setMinimumSize(new java.awt.Dimension(809, 470));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos de mascota");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(460, 30, 320, 46);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("D.N.I");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 100, 30, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Domicilio");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 290, 60, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre y apellido");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 150, 120, 17);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de Nacimiento");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 190, 140, 17);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Teléfono");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 340, 60, 17);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ciudad");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 240, 50, 17);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        jButton1.setText("Eliminar");
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 370, 120, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        jButton2.setText("Guardar");
        jPanel1.add(jButton2);
        jButton2.setBounds(200, 420, 120, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar cliente.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jPanel1.add(jButton3);
        jButton3.setBounds(70, 370, 120, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        jButton4.setText("Modificar");
        jPanel1.add(jButton4);
        jButton4.setBounds(70, 420, 120, 40);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 40)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Datos de cliente");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 30, 290, 46);

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(460, 80, 320, 40);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(180, 240, 150, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(180, 100, 150, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(180, 290, 150, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(180, 340, 150, 20);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(180, 150, 150, 20);

        txt_dia.setBackground(new java.awt.Color(204, 204, 204));
        txt_dia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_dia.setForeground(new java.awt.Color(255, 255, 255));
        txt_dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "2", "24", "25", "26", "27", "28", "29", "30", "31" }));
        txt_dia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_diaKeyPressed(evt);
            }
        });
        jPanel1.add(txt_dia);
        txt_dia.setBounds(180, 180, 50, 40);

        txt_mes.setBackground(new java.awt.Color(204, 204, 204));
        txt_mes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_mes.setForeground(new java.awt.Color(255, 255, 255));
        txt_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        txt_mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_mesKeyPressed(evt);
            }
        });
        jPanel1.add(txt_mes);
        txt_mes.setBounds(240, 180, 50, 40);

        txt_año.setBackground(new java.awt.Color(204, 204, 204));
        txt_año.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_año.setForeground(new java.awt.Color(255, 255, 255));
        txt_año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_añoActionPerformed(evt);
            }
        });
        txt_año.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_añoKeyPressed(evt);
            }
        });
        jPanel1.add(txt_año);
        txt_año.setBounds(300, 180, 90, 40);

        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Edad");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 170, 33, 17);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Nombre");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(0, 10, 50, 17);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Especie");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 50, 50, 17);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Raza");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(0, 90, 40, 17);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Sexo");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(0, 130, 40, 17);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        jButton5.setText("Guardar");
        jPanel2.add(jButton5);
        jButton5.setBounds(190, 270, 120, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar cliente.png"))); // NOI18N
        jButton6.setText("Cancelar");
        jPanel2.add(jButton6);
        jButton6.setBounds(40, 210, 120, 40);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        jButton7.setText("Eliminar");
        jPanel2.add(jButton7);
        jButton7.setBounds(190, 210, 120, 40);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        jButton8.setText("Modificar");
        jPanel2.add(jButton8);
        jButton8.setBounds(40, 270, 120, 40);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(60, 50, 150, 20);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(60, 90, 150, 20);
        jPanel2.add(jTextField8);
        jTextField8.setBounds(60, 130, 150, 20);
        jPanel2.add(jTextField9);
        jTextField9.setBounds(60, 170, 150, 20);
        jPanel2.add(jTextField10);
        jTextField10.setBounds(60, 10, 150, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(460, 130, 320, 320);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, -10, 830, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_diaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_diaKeyPressed
          // TODO add your handling code here:
    }//GEN-LAST:event_txt_diaKeyPressed

    private void txt_mesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mesKeyPressed
      // TODO add your handling code here:
    }//GEN-LAST:event_txt_mesKeyPressed

    private void txt_añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_añoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_añoActionPerformed

    private void txt_añoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_añoKeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_txt_añoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    public static javax.swing.JComboBox<String> txt_año;
    public static javax.swing.JComboBox<String> txt_dia;
    public static javax.swing.JComboBox<String> txt_mes;
    // End of variables declaration//GEN-END:variables
}
