/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;


import com.sun.glass.events.KeyEvent;







/**
 *
 * @author Flores
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bt_cliente = new javax.swing.JButton();
        bt_cerrarsesion = new javax.swing.JButton();
        bt_stock = new javax.swing.JButton();
        bt_historiaclinica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setLayout(null);

        bt_cliente.setBackground(new java.awt.Color(0, 0, 0));
        bt_cliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bt_cliente.setForeground(new java.awt.Color(255, 255, 255));
        bt_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        bt_cliente.setText("1:Clientes");
        bt_cliente.setBorder(null);
        bt_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clienteActionPerformed(evt);
            }
        });
        jPanel2.add(bt_cliente);
        bt_cliente.setBounds(120, 130, 250, 130);

        bt_cerrarsesion.setBackground(new java.awt.Color(0, 0, 0));
        bt_cerrarsesion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bt_cerrarsesion.setForeground(new java.awt.Color(255, 255, 255));
        bt_cerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir sesion.png"))); // NOI18N
        bt_cerrarsesion.setText("4:Cerrar sesión");
        bt_cerrarsesion.setBorder(null);
        bt_cerrarsesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cerrarsesionActionPerformed(evt);
            }
        });
        jPanel2.add(bt_cerrarsesion);
        bt_cerrarsesion.setBounds(410, 300, 250, 130);

        bt_stock.setBackground(new java.awt.Color(0, 0, 0));
        bt_stock.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bt_stock.setForeground(new java.awt.Color(255, 255, 255));
        bt_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stock.png"))); // NOI18N
        bt_stock.setText("3:Stock");
        bt_stock.setBorder(null);
        bt_stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(bt_stock);
        bt_stock.setBounds(120, 300, 250, 130);

        bt_historiaclinica.setBackground(new java.awt.Color(0, 0, 0));
        bt_historiaclinica.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bt_historiaclinica.setForeground(new java.awt.Color(255, 255, 255));
        bt_historiaclinica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/historia clinica.png"))); // NOI18N
        bt_historiaclinica.setText("2:Historia clinica");
        bt_historiaclinica.setBorder(null);
        bt_historiaclinica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(bt_historiaclinica);
        bt_historiaclinica.setBounds(410, 130, 250, 130);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menú");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(310, 30, 150, 69);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 820, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cerrarsesionActionPerformed
        Inicio inicio=new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_cerrarsesionActionPerformed

    private void bt_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clienteActionPerformed
        Menu_Cliente menu_Cliente=new Menu_Cliente();
        menu_Cliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_clienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cerrarsesion;
    private javax.swing.JButton bt_cliente;
    private javax.swing.JButton bt_historiaclinica;
    private javax.swing.JButton bt_stock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
