/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import static Pantallas.Inicio.bt_entrar;
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Developer
 */
public class Recuperar_Cuenta extends javax.swing.JFrame {

    /**
     * Creates new form Recuperar_Cuenta
     */
    public Recuperar_Cuenta() {
        initComponents();
        lb_bien.setVisible(false);
        lb_bien2.setVisible(false);
        lb_mal.setVisible(false);
        lb_mal2.setVisible(false);
        txt_respuesta.setVisible(false);
        lb_pregunta.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_respuesta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lb_pregunta = new javax.swing.JLabel();
        txt_usuariorecup1 = new javax.swing.JTextField();
        bt_verificar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lb_mal = new javax.swing.JLabel();
        lb_bien = new javax.swing.JLabel();
        lb_mal2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lb_bien2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recuperarion de cuenta - MuthanDevs");
        setMaximumSize(new java.awt.Dimension(554, 370));
        setMinimumSize(new java.awt.Dimension(554, 370));
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Recuperación de cuenta");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 20, 480, 43);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 290, 149, 40);

        txt_respuesta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_respuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_respuestaKeyPressed(evt);
            }
        });
        jPanel1.add(txt_respuesta);
        txt_respuesta.setBounds(20, 190, 147, 31);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ingrese su usuario");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 70, 147, 17);

        lb_pregunta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lb_pregunta.setForeground(new java.awt.Color(255, 255, 255));
        lb_pregunta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lb_pregunta);
        lb_pregunta.setBounds(20, 150, 470, 36);

        txt_usuariorecup1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_usuariorecup1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usuariorecup1KeyPressed(evt);
            }
        });
        jPanel1.add(txt_usuariorecup1);
        txt_usuariorecup1.setBounds(50, 100, 119, 31);

        bt_verificar.setBackground(new java.awt.Color(0, 0, 0));
        bt_verificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_verificar.setForeground(new java.awt.Color(255, 255, 255));
        bt_verificar.setText("Verificar");
        bt_verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_verificarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_verificar);
        bt_verificar.setBounds(20, 240, 147, 39);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 100, 24, 32);

        lb_mal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lb_mal.setForeground(new java.awt.Color(255, 255, 255));
        lb_mal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mal recuperar.png"))); // NOI18N
        lb_mal.setText("¡Usuario incorrecto!");
        jPanel1.add(lb_mal);
        lb_mal.setBounds(170, 100, 160, 31);

        lb_bien.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lb_bien.setForeground(new java.awt.Color(255, 255, 255));
        lb_bien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bien recuperar.png"))); // NOI18N
        lb_bien.setText("¡Bien!");
        jPanel1.add(lb_bien);
        lb_bien.setBounds(170, 100, 66, 31);

        lb_mal2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lb_mal2.setForeground(new java.awt.Color(255, 255, 255));
        lb_mal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mal recuperar.png"))); // NOI18N
        lb_mal2.setText("¡Respuesta incorrecta!");
        jPanel1.add(lb_mal2);
        lb_mal2.setBounds(170, 190, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, -6, 570, 380);

        lb_bien2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lb_bien2.setForeground(new java.awt.Color(255, 255, 255));
        lb_bien2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bien recuperar.png"))); // NOI18N
        lb_bien2.setText("¡Bien!");
        jPanel1.add(lb_bien2);
        lb_bien2.setBounds(170, 190, 180, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void RecuperarCuenta(){
        String usuario=txt_usuariorecup1.getText();
        String respuesta=txt_respuesta.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection link = DriverManager.getConnection("jdbc:mysql://localhost/veterinaria_bd","root","root");
            PreparedStatement stmt=link.prepareStatement("SELECT * FROM cuentas WHERE Usuario='"+usuario+"'");
            ResultSet rs=stmt.executeQuery();
            String usuariobd = null,passbd = null,preguntabd = null,respuestabd = null;
            while (rs.next()) {                
                usuariobd=rs.getString("Usuario");
                passbd=rs.getString("Contraseña");
                preguntabd=rs.getString("Pregunta_sec");
                respuestabd=rs.getString("Resp_sec");
            }
            if (usuario.equals(usuariobd)) {
                lb_mal.setVisible(false);
                lb_bien.setVisible(true);
                lb_pregunta.setVisible(true);
                txt_respuesta.setVisible(true);
                lb_pregunta.setText(preguntabd);

                if (respuestabd.equals(respuesta)) {
                    lb_mal2.setVisible(false);
                    lb_bien2.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Su contraseña es: "+passbd);
                    
                }else{
                    if (respuesta.equals("")) {
                    }else{
                       lb_mal2.setVisible(true);
                    }
                }
            }else{
                lb_mal.setVisible(true);
                lb_bien.setVisible(false);
            }
        } catch (Exception e) {
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Inicio inicio=new Inicio();
        this.setVisible(false);
        inicio.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_respuestaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_respuestaKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
           bt_verificar.doClick();
        }
    }//GEN-LAST:event_txt_respuestaKeyPressed

    private void txt_usuariorecup1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuariorecup1KeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
           bt_verificar.doClick();
        }
    }//GEN-LAST:event_txt_usuariorecup1KeyPressed

    private void bt_verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_verificarActionPerformed
        RecuperarCuenta();
    }//GEN-LAST:event_bt_verificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recuperar_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recuperar_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recuperar_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recuperar_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recuperar_Cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_verificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_bien;
    private javax.swing.JLabel lb_bien2;
    private javax.swing.JLabel lb_mal;
    private javax.swing.JLabel lb_mal2;
    private javax.swing.JLabel lb_pregunta;
    private javax.swing.JTextField txt_respuesta;
    private javax.swing.JTextField txt_usuariorecup1;
    // End of variables declaration//GEN-END:variables
}
